theme: jekyll-theme-minimal
title: Kiran Mane — Software Engineer & AI Enthusiast
description: Kiran Mane's CV, projects, courses, and professional journey in AI, data science, and software engineering.